plugins {
    id 'com.android.library'
}

android {
    namespace 'com.google.zxing'
    compileSdk 37

    defaultConfig {
        minSdk 23
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    // zxing 核心库，app 模块通过 api 传递依赖
    api 'com.google.zxing:core:3.5.4'
    implementation 'androidx.appcompat:appcompat:1.8.0'

    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.2.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.6.1'
}
